// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18NciEMz_UCvzn8RJA3s0BYU0yuw4RRw',
    appId: '1:596527339946:web:078a71fa2ecfe026d433d3',
    messagingSenderId: '596527339946',
    projectId: 'sports-app-9a328',
    authDomain: 'sports-app-9a328.firebaseapp.com',
    storageBucket: 'sports-app-9a328.firebasestorage.app',
    measurementId: 'G-D27CVTSNTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOrDnEu8RovkQV4Bm6fgGLzt3gfh9PJk',
    appId: '1:596527339946:android:b92a93765325b9c4d433d3',
    messagingSenderId: '596527339946',
    projectId: 'sports-app-9a328',
    storageBucket: 'sports-app-9a328.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXn_r-fPmnbYMvwOIyNHlUFePnVEBANc',
    appId: '1:596527339946:ios:ba031d8987ed0eebd433d3',
    messagingSenderId: '596527339946',
    projectId: 'sports-app-9a328',
    storageBucket: 'sports-app-9a328.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdXn_r-fPmnbYMvwOIyNHlUFePnVEBANc',
    appId: '1:596527339946:ios:ba031d8987ed0eebd433d3',
    messagingSenderId: '596527339946',
    projectId: 'sports-app-9a328',
    storageBucket: 'sports-app-9a328.firebasestorage.app',
    iosBundleId: 'com.example.sampleApp',
  );
}
